server:
  port: 8081
spring:
  application:
    name: admin-server
  # Spring security配置信息
  security:
    user:
      name: "admin"
      password: "admin"
  #mail邮箱配置(用于异常报警,发送邮件及时通知)
  mail:
    host:  smtp.qq.com #qq的固定写法
    username: xxxxxx@qq.com #发送邮件的qq邮箱
    password: xjwbriexiwvtbafd #授权码
  boot:
    admin:
      notify:
        mail:
          to: xxxxxx@qq.com #接受邮件的qq邮箱
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8080}/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    # 注册中心加入metadata-map的信息，验证
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password:  ${spring.security.user.password}
management:
  endpoints:
    web:
      exposure:
        include: '*' #显示健康节点（* 表示所有）
  endpoint:
    health:
      # never:细节永远不会显示
      # always;详细信息显示给所有用户
      # when_authorized:仅向授权用户显示详细信息。可以使用management.endpoint.health.roles配置授权角色。
      show-details: always